# Generated by Django 2.2.7 on 2020-01-15 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('degreeId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offerId', models.IntegerField(primary_key=True, serialize=False)),
                ('degrees', models.ManyToManyField(to='offers.Degree')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('degrees', models.ManyToManyField(to='offers.Degree')),
            ],
        ),
        migrations.CreateModel(
            name='User_offer',
            fields=[
                ('userOfferId', models.IntegerField(primary_key=True, serialize=False)),
                ('like', models.BooleanField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.Offer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.User')),
            ],
        ),
    ]
