# Generated by Django 2.2.7 on 2020-01-17 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20200115_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='city',
            field=models.TextField(blank=True, default='City', null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='country',
            field=models.TextField(blank=True, default='Country', null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, default='Description', null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='enterprise',
            field=models.TextField(blank=True, default='Enterprise', null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='immediate',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='months',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='province',
            field=models.TextField(blank=True, default='Province', null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='salary',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='university',
            field=models.TextField(blank=True, default='University', null=True),
        ),
    ]
