# Generated by Django 2.2.7 on 2020-01-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20200120_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
