# Generated by Django 2.2.7 on 2020-01-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_auto_20200120_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
