# Generated by Django 2.2.7 on 2020-01-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_auto_20200121_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
