# Generated by Django 2.2.7 on 2019-11-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standarduser',
            name='categories',
            field=models.ManyToManyField(blank=True, to='films.Category'),
        ),
    ]
