# Generated by Django 2.2.7 on 2020-01-10 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('url', models.URLField()),
                ('pictureUrl', models.URLField()),
                ('nombre', models.TextField(max_length=100)),
                ('idArtista', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('tagValue', models.TextField(max_length=100)),
                ('idTag', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEtiquetaArtista',
            fields=[
                ('fecha', models.DateField()),
                ('idUsuarioEtiquetaArtista', models.IntegerField(primary_key=True, serialize=False)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendation.Artista')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendation.Etiqueta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendation.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioArtista',
            fields=[
                ('tiempoEscucha', models.IntegerField()),
                ('idUsuarioArtista', models.IntegerField(primary_key=True, serialize=False)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendation.Artista')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recomendation.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='artista',
            field=models.ManyToManyField(through='recomendation.UsuarioArtista', to='recomendation.Artista'),
        ),
        migrations.AddField(
            model_name='artista',
            name='etiquetasFrec',
            field=models.ManyToManyField(to='recomendation.Etiqueta'),
        ),
    ]
