# Generated by Django 2.2.7 on 2020-01-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarioartista',
            old_name='idArtista',
            new_name='artista',
        ),
        migrations.RenameField(
            model_name='usuarioartista',
            old_name='idUsuario',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='usuarioetiquetaartista',
            old_name='idArtista',
            new_name='artista',
        ),
        migrations.RenameField(
            model_name='usuarioetiquetaartista',
            old_name='idTag',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='usuarioetiquetaartista',
            old_name='idUsuario',
            new_name='usuario',
        ),
    ]
