# Generated by Django 2.2.7 on 2019-11-25 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='categories',
        ),
    ]
