# Generated by Django 2.2.7 on 2019-11-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_remove_rate_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='film',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
